import { createMiddleware } from "hono/factory";
import { createRemoteJWKSet, jwtVerify } from "jose";

/**
 * Base type definition for user information obtained from JWT payload
 */
export interface JwtUser {
  sub: string;
  id?: string;
  userId?: string;
  email?: string;
  role?: string;
  iat?: number;
  exp?: number;
  [key: string]: unknown;
}

/**
 * Extended JWT user type (includes all better-auth fields)
 */
export interface ExtendedJwtUser extends JwtUser {
  name?: string;
  emailVerified?: boolean;
  image?: string | null;
  banned?: boolean;
  banReason?: string | null;
  banExpires?: string | null;
  createdAt?: string;
  updatedAt?: string;
  iss?: string;
  aud?: string;
}

// better-auth's JWT plugin uses the EdDSA algorithm and requires obtaining the public key from the JWKS endpoint
const authUrl = process.env.BETTER_AUTH_URL || "http://localhost:10000";
const jwksUrl = new URL("/api/auth/jwks", authUrl);

// Create remote JWK set to obtain public key from JWKS endpoint
const JWKS = createRemoteJWKSet(jwksUrl);

/**
 * Hono Middleware: Verify Bearer Token and set User information in Context
 * Verifies EdDSA-signed JWT generated by better-auth's JWT plugin
 *
 * Sets `user` and `userId` in Context in a type-safe manner.
 *
 * @param serviceName - Service name for log output (optional)
 */
export const verifyJwt = (serviceName?: string) =>
  createMiddleware<{
    Variables: {
      user: JwtUser;
      userId: string;
    };
  }>(async (c, next) => {
    const authHeader = c.req.header("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return c.json({ error: "Unauthorized: Missing or invalid header" }, 401);
    }

    const token = authHeader.split(" ")[1];
    if (!token) {
      return c.json({ error: "Unauthorized: Missing token" }, 401);
    }

    try {
      // Verify EdDSA-signed JWT with public key obtained from JWKS endpoint
      const { payload } = await jwtVerify(token, JWKS, {
        // Match the algorithm used by better-auth's JWT plugin
        algorithms: ["EdDSA"],
      });

      // better-auth's JWT payload has a `sub` or `id` field
      const userId =
        (typeof payload.sub === "string" ? payload.sub : null) ||
        (typeof payload.id === "string" ? payload.id : null) ||
        (typeof payload.userId === "string" ? payload.userId : null);

      if (!userId) {
        const logPrefix = serviceName ? `[${serviceName} Middleware]` : "[Middleware]";
        console.error(`${logPrefix} No user ID found in JWT payload:`, payload);
        return c.json({ error: "Unauthorized: Invalid token payload" }, 401);
      }

      // Set in Context (available for subsequent handlers)
      const user: JwtUser = { ...payload, sub: userId };
      c.set("user", user);
      c.set("userId", userId);

      await next();
    } catch (e) {
      const logPrefix = serviceName ? `[${serviceName} Middleware]` : "[Middleware]";
      console.error(`${logPrefix} JWT Verification Failed:`, e);
      return c.json({ error: "Unauthorized: Invalid token" }, 401);
    }
  });
